### PR TITLE
Overwrite db config in api/config/config.yaml in install script

### PR DESCRIPTION
**Pull request by oyvang**

### CODE REVIEW

**Comment by oyvang** [comment]
I am closing this PR. just found out that there is a docker-config.yaml

**Comment by thordy** [comment]
This script is mainly to be used for development setups locally for easier getting started.

The API already supports having [multiple configuration files](https://github.com/kcapp/api/tree/main/config), so I don't think we should override the values in the default config.

Maybe it's a better idea to change the default port of the [Dev DB](https://github.com/kcapp/database/blob/main/docker-compose.yml#L13) to be `3306`? Problem is just if the port is occupied by another process we runinto issues. So we could  instead create a new `config-docker-db.yaml` to the installer which should be used?
Alternatively we could make the script prompt for port to use for the docker-db, and configure based on that, but that requires some more work

For production setups, I don't recommend using this, but instead using the proper [Docker-Compose](https://github.com/kcapp/services/blob/main/docker-compose.yaml) setup, which is configured via [env-files](https://github.com/kcapp/services/blob/main/.env-dist) or setting it up manually, which is better if you want to keep `db`,/`api` /`frontend` separated

**Comment by oyvang** [comment]
I can agree that this is not a beautiful way of doing it. However if we are going to create a new config file or prompt for port to use we regardless need to have this information in the config.yaml if I am not mistaken. The existing [config.docker.yaml](https://github.com/oyvang/api/blob/main/config/config.docker.yaml) is there, but is only used in the dockerfile to replace the [config.yaml](https://github.com/oyvang/api/blob/main/config/config.yaml) which is used by the api.

for production I when with a manual approach, I made this PR just because I wanted a quick setup to work with the install script which is not the case without modifications today.

as a side note, there are other issues in the install script if we want to run it on a mac, not sure if it will be the case on every macbook though.

1. `docker-compose --log-level CRITICAL up -d` the log part here is not a part of docker-compose v2 for mac which is enabled by default. So I had to turn this off.
2. `kill $(ps -s $CURRENT_SID -o pid=)` the sesslist parameter does not exist by default on a mac.

That said, I am not sure if this is supposed to support mac by default or not. Over to the actual, question. Which approach do you prefer to take? Would it be an idea to change API, do load the `config.yaml` by default and if it is possible to start the API with some parameter to load other files. for example. env=script-test then the install script can create the yaml file named config-script-test.yaml or something. Idk. This way we will not overwrite any other setting and the install script do create a script to run the api which we can also attach this parameter.

**Comment by oyvang** [comment]
Anyhow, I'll close this PR.

**Pull request closed without merging**
